### ISSUE TITLE
Unable to see icon picker in custom field.

### ISSUE THREAD

**Issue by joshharrisici** [awethemes/wp-simple-iconfonts#3]
I have installed and activated the plugin, configured a custom field to use the Icon Picker type, and used the Font Icon Manager to upload a custom generated Icomoon font file. But when I go to edit the page, the picker does not display in the field:

![picker](https://user-images.githubusercontent.com/37448887/39254288-bf837e4e-4877-11e8-8d8b-1499e2f51652.jpg)
![font-icon-manager](https://user-images.githubusercontent.com/37448887/39254286-bf6cb4b6-4877-11e8-8e5c-978a87fe54a3.jpg)
![no-picker](https://user-images.githubusercontent.com/37448887/39254287-bf7719ba-4877-11e8-9e13-075cd0fa183e.jpg)

The documentation provides a function to add to display the picker, but it does not say which PHP file to add the function to. What am I missing?

**Comment by anhskohbo** [comment]
Hi, are you using in a group field in ACF? If that I think we have trouble in render picker in group field.

**Comment by anhskohbo** [comment]
Fixed https://github.com/awethemes/wp-simple-iconfonts/commit/b48ac2f87ba911e84d59d03ea29849beed09adc5

Please update to v0.5.0
