### ISSUE TITLE
Divi compatibility

### ISSUE THREAD

**Issue by spotUP** [awethemes/wp-simple-iconfonts#4]
Hi! This plugin is quite fantastic! Just what i need for my custom icons.
Uploading and using my icons works until I add a bunch of icons on a page in the divi builder, all of them ends up at the top left?

**Comment by nuclearstudio** [comment]
See the issue topic here, I believe this may be the solve you are looking for:
https://github.com/awethemes/wp-simple-iconfonts/issues/5

**Comment by spotUP** [comment]
Thank you!

Skickat från min iPhone
