### ISSUE TITLE
Shortcode outputting above content

### ISSUE THREAD

**Issue by nuclearstudio** [awethemes/wp-simple-iconfonts#5]
There is presently an issue with the output of shortcodes, outputting above the content.

The issue is in "inc/Support/Shortcode_Icon.php".

Lines 114: 
```
echo wp_get_attachment_image( $atts['icon'] );
```
Line 123: 
```
printf( '<i class="%1$s %2$s" %3$s></i>', esc_attr( $atts['type'] ), esc_attr( $atts['icon'] ), $css ); // WPCS: xss ok.
```

Shortcode callbacks have to return, not output. 
More info: http://codex.wordpress.org/Shortcode_API

I advise the following:

Line 114: 
```
return wp_get_attachment_image( $atts['icon'] );
```
Line 123: 
```
return sprintf( '<i class="%1$s %2$s" %3$s></i>', esc_attr( $atts['type'] ), esc_attr( $atts['icon'] ), $css ); // WPCS: xss ok.
```

**Comment by anhskohbo** [comment]
Fixed, many thanks!

**Comment by nuclearstudio** [comment]
Super! That was fast.

If I might be so bold to include a couple of further suggestions/improvements.

1. It would be helpful to target your shortcodes via a consistent css class system, ie 'wp-simple-iconfonts'
_(Note my temporary work-around - not an ideal method of application)_
```
return sprintf( '<i class="wp-simple-iconfonts %1$s %2$s" %3$s></i>', esc_attr( $atts['type'] ), esc_attr( $atts['icon'] ), $css ); // WPCS: xss ok.
```
2. Furthermore, it would be nice to have the option of a custom class per shortcode. Introducing a class field within the shortcode view settings panel.

3. Generally when inserting a shortcode icon, I prefer them to appear at the same font-size as their inline text, effectively 1em or 1rem or 1ch (whatever the inherit css value is). Whereas, your shortcode settings panel view is pre-filled with the Font Size value 14px and Font Weight 400, perhaps it best to just to leave these values blank by default. Effectively falling back on the current inline inheritance. Then if a value is set, the inline CSS is dominant. This method would reduce unnecessary inline css.

Keep up the great work. I'll be sure to write you a WP review.
